services:
  - type: web
    name: inventory-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
